/*
* indexer.c     Andy Xu     May 1, 2023
*
* Description: This file implements the indexer, which creates an index of words and documents
* based on the resulting files generated by crawler. It contains the functions main, parseArgs,
* indexBuild, and indexPage, which are described in the implementation below.
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h> 
#include "index.h"
#include "word.h"
#include "pagedir.h"
#include "file.h"
#include "mem.h"
#include "webpage.h"
#include "counters.h"
#include "hashtable.h"

/*** function prototypes ***/
static void parseArgs(const int argc, char* argv[], char** pageDirectory, char** indexFilename);
static index_t* indexBuild(char* pageDirectory);
static void indexPage(webpage_t* curPage, int docID, index_t* index);

/*
* main() - calls parseArgs, indexBuild, index_save, and index_delete; then exits zero
*/
int 
main(const int argc, char* argv[])
{
    char* pageDirectory = NULL;  
    char* indexFileName = NULL; 
    parseArgs(argc, argv, &pageDirectory, &indexFileName);
    index_t* index = indexBuild(pageDirectory);
    index_save(index, indexFileName);
    index_delete(index);
    exit(0);
}

/*
* parseArgs() - extracts and validates function parameters given the initial parameters from main
*/
static 
void parseArgs(const int argc, char* argv[], char** pageDirectory, char** indexFilename)
{
    if (argc != 3) {
        fprintf(stderr, "Error: wrong number of arguments. Must only have two arguments: pageDirectory and indexFilename.");
        exit(1);
    }

    *pageDirectory = argv[1];
    if (!pagedir_validate(*pageDirectory)) {
        fprintf(stderr, "Error: pageDirectory is invalid, either does not exist or is not crawler produced.");
        exit(2);
    }

    *indexFilename = argv[2];
    FILE* fp = fopen(*indexFilename, "w");
    if (fp != NULL) { 
        fclose(fp);
    }
    else {
        fprintf(stderr, "Error: indexFilename is invalid.");
        exit(3);
    }
}

/*
* indexBuild() - given a valid pageDirectory, indexBuild builds the index by looping over all 
* files in the pageDirectory and passsing the loaded webpage and docID to indexPage
*/
static 
index_t* indexBuild(char* pageDirectory)
{
    //creates a new 'index' object
    index_t* ind = mem_assert(index_new(700), "cannot create new index");

    //loops over document ID numbers, counting from 1
    int curId = 0;
    webpage_t* curPage = NULL;
    while ((curPage = pagedir_load(pageDirectory, ++curId)) != NULL) 
    {
        //if webpage is successfully loaded from the document file 'pageDirectory/id'
        //pass webpage and docId to indexPage
        indexPage(curPage, curId, ind);
        webpage_delete(curPage);
    }
    
    return ind;
}

/*
* indexPage() - given a webpage curPage, a docID, and an index, indexPage counts the 
* number of times each word appears in the given webpage and updates the index accordingly.
*/
static 
void indexPage(webpage_t* curPage, int docID, index_t* index)
{
    //steps through each word of the webpage
    int curPos = 0;
    char* word = NULL;
    while ((word = webpage_getNextWord(curPage, &curPos)) != NULL) {
        //skips trivial words (less than length 3),
        if (strlen(word) >= 3) {
            char* normWord = normalizeWord(word); //normalizes the word (converts to lower case),
            counters_t* wordCounter = index_find(index, word); //looks up the word in the index,
            //adding the word to the index if needed
            if (wordCounter == NULL) {
                wordCounter = mem_assert(counters_new(), "cannot create new counter");
                index_insert(index, normWord, wordCounter);
            }    
            //increments the count of occurrences of this word in this docID
            counters_add(wordCounter, docID);
        }
        mem_free(word);
    }
}





